# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiaryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiaryApp
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKCommon'
  pod 'GoogleSignIn'
  pod 'naveridlogin-sdk-ios'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Toast-Swift', '~> 5.0.1'
end
